### ISSUE TITLE
Whitespace formatting

### ISSUE THREAD

**Issue by grawk** [paypal/nemo-screenshot#2]
Move this over to 4 space tabs with 2 space continuation tabs. Current formatting is hard to look at.

**Comment by ibihim** [comment]
Yes, would love that. ^^ I would like to add a PR for that :D

**Comment by grawk** [comment]
Would appreciate it!

**Comment by ibihim** [comment]
Added a small PR with minor changes, if that gets through, there is already a white space branch in place. Basically WebStorm was doing the job :)

**Comment by grawk** [comment]
Hey @ibihim please let me know if you'd like me to include your email address as well as your name in the contributors block of package.json. Thanks.

**Comment by ibihim** [comment]
Hi, I would love to have so! Thanks a lot.

**Comment by ibihim** [comment]
Krzysztof Ostrowski, krzysztof.ostrowski@posteo.de,

I guess this issue can be closed :)
