### ISSUE TITLE
Nemo screenshot integration with Nemo 1.0.*

### ISSUE THREAD

**Issue by ibihim** [paypal/nemo-screenshot#6]
Hi,
could you update the nemo-screenshot plugin integration for Nemo 1.0.*?
Parsing the object blindly into the config/config.json doesn't work: "Nemo plugin threw error during setup".
I would assume that "register": "true" isn't true any more ;)

**Comment by ibihim** [comment]
(update README.md)

**Comment by grawk** [comment]
Hi @ibihim. You are correct. The README is out of date with the 1.0 upgrade. I did upgrade and release nemo-screenshot for nemo 1.0 but haven't had a chance to update the docs yet. I hope to fix the docs this week. In the meantime, you can use the unit tests as a basis to understand new configuration as well as changes to the API. The changes are on the `1.0-develop` branch. I will do my best to upgrade documentation today.

**Comment by grawk** [comment]
@ibihim just some updates. I have moved the 1.0 version to the `develop` branch and deleted the `1.0-develop` branch. There is a PR open to move `develop` to `master`. Please see the `develop` branch README for updated documentation: https://github.com/paypal/nemo-screenshot/blob/develop/README.md

**Comment by ibihim** [comment]
Okay, awesome. Thanks a lot. That was quick. So I might drop the nemo.driver.takeScreenshot method again :+1:
