### ISSUE TITLE
Screenshot 'on exception' doesn't work:

### ISSUE THREAD

**Issue by ruslK** [paypal/nemo-screenshot#71]
with config: 
```
"screenshot": {
            "module": "nemo-screenshot",
            "register": true,
            "arguments": [
                "path:report/screenshots", [ "exception"]] }
```

there is no screenshot on exception. 
But screenshot working on click, or nemo.snap.

**Comment by grawk** [comment]
Hi @ruslK.

I think it would be preferable to put this feature into the core `nemo` module, along with the `snap` feature: https://github.com/krakenjs/nemo/blob/master/README.md#screenshots

Would that work?

**Comment by ruslK** [comment]
Open under nemo repo.
